defmodule TcmEdu.Repo.TenantMigrations.ClassGroupFkNilify do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:users, "users_class_group_id_fkey")

    alter table(:users, prefix: prefix()) do
      modify :class_group_id,
             references(:class_groups,
               column: :id,
               name: "users_class_group_id_fkey",
               type: :uuid,
               prefix: prefix(),
               on_delete: :nilify_all
             )
    end
  end

  def down do
    drop constraint(:users, "users_class_group_id_fkey")

    alter table(:users, prefix: prefix()) do
      modify :class_group_id,
             references(:class_groups,
               column: :id,
               name: "users_class_group_id_fkey",
               type: :uuid,
               prefix: prefix()
             )
    end
  end
end
