defmodule TcmEdu.Repo.TenantMigrations.FinalizeSpResources do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:simulated_patients, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :subject, :text
      add :scenario_title, :text
      add :profile, :map, default: %{}
      add :complaint, :text, null: false
      add :history, :text
      add :personality, :text
      add :talking_style, :text
      add :key_points, {:array, :text}, default: []
      add :rubric, :map
      add :difficulty, :bigint, default: 3
      add :min_questions, :bigint, default: 8
      add :max_turns, :bigint, default: 40
      add :status, :text, default: "draft"

      add :created_by_id,
          references(:users,
            column: :id,
            name: "simulated_patients_created_by_id_fkey",
            type: :uuid,
            prefix: prefix()
          ),
          null: false

      add :created_by_email, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:simulated_patient_sessions, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :patient_snapshot, :map, null: false
      add :status, :text, default: "active"
      add :turn_count, :bigint, default: 0
      add :ended_at, :utc_datetime
      add :ended_reason, :text
      add :evaluation_status, :text, default: "none"
      add :evaluation_error, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :assignment_id, :uuid
      add :patient_id, :uuid, null: false
      add :student_id, :uuid, null: false
    end

    create table(:simulated_patient_messages, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :role, :text, null: false
      add :content, :text, null: false
      add :turn_index, :bigint, default: 0
      add :metadata, :map, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :session_id,
          references(:simulated_patient_sessions,
            column: :id,
            name: "simulated_patient_messages_session_id_fkey",
            type: :uuid,
            prefix: prefix()
          ),
          null: false
    end

    create table(:simulated_patient_evaluations, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :professional_score, :bigint
      add :empathy_score, :bigint
      add :communication_score, :bigint
      add :total_score, :decimal
      add :rubric_snapshot, :map
      add :grade, :text
      add :feedback, :text
      add :highlights, {:array, :text}, default: []
      add :weaknesses, {:array, :text}, default: []
      add :key_points_hit, {:array, :text}, default: []
      add :key_points_missed, {:array, :text}, default: []
      add :transcript_tokens, :bigint
      add :model, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :session_id,
          references(:simulated_patient_sessions,
            column: :id,
            name: "simulated_patient_evaluations_session_id_fkey",
            type: :uuid,
            prefix: prefix()
          ),
          null: false

      add :patient_id,
          references(:simulated_patients,
            column: :id,
            name: "simulated_patient_evaluations_patient_id_fkey",
            type: :uuid,
            prefix: prefix()
          ),
          null: false

      add :student_id,
          references(:users,
            column: :id,
            name: "simulated_patient_evaluations_student_id_fkey",
            type: :uuid,
            prefix: prefix()
          ),
          null: false
    end

    create table(:simulated_patient_assignments, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:simulated_patient_sessions, prefix: prefix()) do
      modify :assignment_id,
             references(:simulated_patient_assignments,
               column: :id,
               name: "simulated_patient_sessions_assignment_id_fkey",
               type: :uuid,
               prefix: prefix()
             )

      modify :patient_id,
             references(:simulated_patients,
               column: :id,
               name: "simulated_patient_sessions_patient_id_fkey",
               type: :uuid,
               prefix: prefix()
             )

      modify :student_id,
             references(:users,
               column: :id,
               name: "simulated_patient_sessions_student_id_fkey",
               type: :uuid,
               prefix: prefix()
             )
    end

    alter table(:simulated_patient_assignments, prefix: prefix()) do
      add :deadline, :utc_datetime
      add :status, :text, default: "assigned"
      add :notes, :text

      add :assigned_by_id,
          references(:users,
            column: :id,
            name: "simulated_patient_assignments_assigned_by_id_fkey",
            type: :uuid,
            prefix: prefix()
          ),
          null: false

      add :assigned_by_email, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :patient_id,
          references(:simulated_patients,
            column: :id,
            name: "simulated_patient_assignments_patient_id_fkey",
            type: :uuid,
            prefix: prefix()
          ),
          null: false

      add :student_id,
          references(:users,
            column: :id,
            name: "simulated_patient_assignments_student_id_fkey",
            type: :uuid,
            prefix: prefix()
          ),
          null: false
    end
  end

  def down do
    drop constraint(
           :simulated_patient_assignments,
           "simulated_patient_assignments_assigned_by_id_fkey"
         )

    drop constraint(
           :simulated_patient_assignments,
           "simulated_patient_assignments_patient_id_fkey"
         )

    drop constraint(
           :simulated_patient_assignments,
           "simulated_patient_assignments_student_id_fkey"
         )

    alter table(:simulated_patient_assignments, prefix: prefix()) do
      remove :student_id
      remove :patient_id
      remove :updated_at
      remove :inserted_at
      remove :assigned_by_email
      remove :assigned_by_id
      remove :notes
      remove :status
      remove :deadline
    end

    drop constraint(:simulated_patient_sessions, "simulated_patient_sessions_assignment_id_fkey")

    drop constraint(:simulated_patient_sessions, "simulated_patient_sessions_patient_id_fkey")

    drop constraint(:simulated_patient_sessions, "simulated_patient_sessions_student_id_fkey")

    alter table(:simulated_patient_sessions, prefix: prefix()) do
      modify :student_id, :uuid
      modify :patient_id, :uuid
      modify :assignment_id, :uuid
    end

    drop table(:simulated_patient_assignments, prefix: prefix())

    drop constraint(
           :simulated_patient_evaluations,
           "simulated_patient_evaluations_session_id_fkey"
         )

    drop constraint(
           :simulated_patient_evaluations,
           "simulated_patient_evaluations_patient_id_fkey"
         )

    drop constraint(
           :simulated_patient_evaluations,
           "simulated_patient_evaluations_student_id_fkey"
         )

    drop table(:simulated_patient_evaluations, prefix: prefix())

    drop constraint(:simulated_patient_messages, "simulated_patient_messages_session_id_fkey")

    drop table(:simulated_patient_messages, prefix: prefix())

    drop table(:simulated_patient_sessions, prefix: prefix())

    drop constraint(:simulated_patients, "simulated_patients_created_by_id_fkey")

    drop table(:simulated_patients, prefix: prefix())
  end
end
