defmodule TcmEdu.Repo.TenantMigrations.AddTenantDocMediaAndSwitches do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:tenant_docs, prefix: prefix()) do
      add :media_kind, :text, default: "text"
      add :indexed, :boolean, default: true
      add :in_chat, :boolean, default: true
      add :asset_url, :text
      add :thumbnail_url, :text
    end
  end

  def down do
    alter table(:tenant_docs, prefix: prefix()) do
      remove :thumbnail_url
      remove :asset_url
      remove :in_chat
      remove :indexed
      remove :media_kind
    end
  end
end
