defmodule TcmEdu.Repo.TenantMigrations.ClinicalReasoningMdt do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:simulated_patients, prefix: prefix()) do
      add :difficulty_level, :text, default: "introductory"
      add :standard_pathway, :map, default: %{}
      add :red_flags, {:array, :text}, default: []
    end

    alter table(:simulated_patient_evaluations, prefix: prefix()) do
      add :diagnosis_score, :bigint, default: 0
      add :differential_score, :bigint, default: 0
      add :treatment_score, :bigint, default: 0
      add :stage_scores, :map, default: %{}
      add :reasoning_gaps, {:array, :map}, default: []
      add :standard_pathway_snapshot, :map
    end

    create table(:simulated_patient_case_stages, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :stage, :text, null: false
      add :order, :bigint, null: false
      add :status, :text, default: "locked"
      add :student_actions, {:array, :map}, default: []
      add :reasoning_gaps, {:array, :map}, default: []
      add :completed_at, :utc_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :session_id,
          references(:simulated_patient_sessions,
            column: :id,
            name: "simulated_patient_case_stages_session_id_fkey",
            type: :uuid,
            prefix: prefix()
          ),
          null: false
    end

    create table(:mdt_rooms, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :status, :text, default: "open"
      add :case_snapshot, :map, default: %{}
      add :concluded_at, :utc_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :case_id, :uuid, null: false
      add :owner_id, :uuid, null: false
    end

    create table(:mdt_participants, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :department, :text, null: false
      add :display_name, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :room_id,
          references(:mdt_rooms,
            column: :id,
            name: "mdt_participants_room_id_fkey",
            type: :uuid,
            prefix: prefix()
          ),
          null: false

      add :user_id,
          references(:users,
            column: :id,
            name: "mdt_participants_user_id_fkey",
            type: :uuid,
            prefix: prefix()
          ),
          null: false
    end

    create table(:mdt_messages, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :role, :text, null: false
      add :content, :text, null: false
      add :kind, :text, default: "chat"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :room_id,
          references(:mdt_rooms,
            column: :id,
            name: "mdt_messages_room_id_fkey",
            type: :uuid,
            prefix: prefix()
          ),
          null: false

      add :author_id,
          references(:users,
            column: :id,
            name: "mdt_messages_author_id_fkey",
            type: :uuid,
            prefix: prefix()
          )
    end

    create table(:mdt_conclusions, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :primary_diagnosis, :text
      add :differential, :text
      add :treatment, :text
      add :roles_considered, {:array, :text}, default: []
      add :summary, :text
      add :model, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :room_id,
          references(:mdt_rooms,
            column: :id,
            name: "mdt_conclusions_room_id_fkey",
            type: :uuid,
            prefix: prefix()
          ),
          null: false
    end

    create table(:mdt_cases, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:mdt_rooms, prefix: prefix()) do
      modify :case_id,
             references(:mdt_cases,
               column: :id,
               name: "mdt_rooms_case_id_fkey",
               type: :uuid,
               prefix: prefix()
             )

      modify :owner_id,
             references(:users,
               column: :id,
               name: "mdt_rooms_owner_id_fkey",
               type: :uuid,
               prefix: prefix()
             )
    end

    alter table(:mdt_cases, prefix: prefix()) do
      add :name, :text, null: false
      add :scenario_title, :text
      add :profile, :map, default: %{}
      add :complaint, :text, null: false
      add :history, :text
      add :departments, {:array, :text}, default: []
      add :expected_conclusion, :text
      add :status, :text, default: "draft"

      add :created_by_id,
          references(:users,
            column: :id,
            name: "mdt_cases_created_by_id_fkey",
            type: :uuid,
            prefix: prefix()
          ),
          null: false

      add :created_by_email, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:clinical_reasoning_reports, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :student_id,
          references(:users,
            column: :id,
            name: "clinical_reasoning_reports_student_id_fkey",
            type: :uuid,
            prefix: prefix()
          ),
          null: false

      add :report_period_start, :date
      add :report_period_end, :date
      add :inquiry_score, :bigint, default: 0
      add :physical_exam_score, :bigint, default: 0
      add :auxiliary_score, :bigint, default: 0
      add :diagnosis_score, :bigint, default: 0
      add :differential_score, :bigint, default: 0
      add :treatment_score, :bigint, default: 0
      add :follow_up_score, :bigint, default: 0
      add :total_score, :decimal
      add :grade, :text
      add :rank, :bigint
      add :peer_count, :bigint
      add :statistics, :map, default: %{}
      add :dimension_report, :map, default: %{}
      add :improvement_plan, :text
      add :session_count, :bigint, default: 0
      add :generated_at, :utc_datetime, default: fragment("(now() AT TIME ZONE 'utc')")

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    drop constraint(:clinical_reasoning_reports, "clinical_reasoning_reports_student_id_fkey")

    drop table(:clinical_reasoning_reports, prefix: prefix())

    drop constraint(:mdt_cases, "mdt_cases_created_by_id_fkey")

    alter table(:mdt_cases, prefix: prefix()) do
      remove :updated_at
      remove :inserted_at
      remove :created_by_email
      remove :created_by_id
      remove :status
      remove :expected_conclusion
      remove :departments
      remove :history
      remove :complaint
      remove :profile
      remove :scenario_title
      remove :name
    end

    drop constraint(:mdt_rooms, "mdt_rooms_case_id_fkey")

    drop constraint(:mdt_rooms, "mdt_rooms_owner_id_fkey")

    alter table(:mdt_rooms, prefix: prefix()) do
      modify :owner_id, :uuid
      modify :case_id, :uuid
    end

    drop table(:mdt_cases, prefix: prefix())

    drop constraint(:mdt_conclusions, "mdt_conclusions_room_id_fkey")

    drop table(:mdt_conclusions, prefix: prefix())

    drop constraint(:mdt_messages, "mdt_messages_room_id_fkey")

    drop constraint(:mdt_messages, "mdt_messages_author_id_fkey")

    drop table(:mdt_messages, prefix: prefix())

    drop constraint(:mdt_participants, "mdt_participants_room_id_fkey")

    drop constraint(:mdt_participants, "mdt_participants_user_id_fkey")

    drop table(:mdt_participants, prefix: prefix())

    drop table(:mdt_rooms, prefix: prefix())

    drop constraint(
           :simulated_patient_case_stages,
           "simulated_patient_case_stages_session_id_fkey"
         )

    drop table(:simulated_patient_case_stages, prefix: prefix())

    alter table(:simulated_patient_evaluations, prefix: prefix()) do
      remove :standard_pathway_snapshot
      remove :reasoning_gaps
      remove :stage_scores
      remove :treatment_score
      remove :differential_score
      remove :diagnosis_score
    end

    alter table(:simulated_patients, prefix: prefix()) do
      remove :red_flags
      remove :standard_pathway
      remove :difficulty_level
    end
  end
end
