defmodule TcmEdu.Repo.TenantMigrations.CourseCoverAshStorage do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:courses, prefix: prefix()) do
      remove :cover_image_url
    end
  end

  def down do
    alter table(:courses, prefix: prefix()) do
      add :cover_image_url, :text
    end
  end
end
