defmodule TcmEdu.Repo.TenantMigrations.SimplifyClassGroups do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:class_groups, prefix: prefix()) do
      remove :description
      remove :grade_year
    end
  end

  def down do
    alter table(:class_groups, prefix: prefix()) do
      add :grade_year, :bigint
      add :description, :text
    end
  end
end
