defmodule TcmEdu.Repo.TenantMigrations.AddTenantKnowledgeVectorRag do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:tenant_docs, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :title, :text, null: false
      add :doc_type, :text, default: "other"
      add :content, :text, null: false
      add :source_name, :text
      add :embedding_status, :text, default: "pending"
      add :error_message, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :full_text_vector, :vector, size: 1024
    end
  end

  def down do
    drop table(:tenant_docs, prefix: prefix())
  end
end
