defmodule TcmEdu.Repo.TenantMigrations.AiGenerationJobs do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:ai_generation_jobs, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :kind, :text, null: false
      add :title, :text, null: false
      add :params, :map, default: %{}
      add :result, :map
      add :status, :text, default: "pending"
      add :progress, :bigint, default: 0
      add :error_message, :text
      add :oban_job_id, :bigint

      add :requested_by_id,
          references(:users,
            column: :id,
            name: "ai_generation_jobs_requested_by_id_fkey",
            type: :uuid,
            prefix: prefix()
          ),
          null: false

      add :requested_by_email, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :started_at, :utc_datetime
      add :completed_at, :utc_datetime
    end
  end

  def down do
    drop constraint(:ai_generation_jobs, "ai_generation_jobs_requested_by_id_fkey")

    drop table(:ai_generation_jobs, prefix: prefix())
  end
end
