defmodule TcmEdu.Repo.TenantMigrations.MigrateResources2 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:mdt_rooms, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :status, :text, default: "open"
      add :case_snapshot, :map, default: %{}
      add :concluded_at, :utc_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :case_id, :uuid, null: false
      add :owner_id, :uuid, null: false
    end

    create table(:mdt_participants, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :department, :text, null: false
      add :display_name, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :room_id,
          references(:mdt_rooms,
            column: :id,
            name: "mdt_participants_room_id_fkey",
            type: :uuid,
            prefix: prefix()
          ),
          null: false

      add :user_id,
          references(:users,
            column: :id,
            name: "mdt_participants_user_id_fkey",
            type: :uuid,
            prefix: prefix()
          ),
          null: false
    end

    create table(:mdt_messages, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :role, :text, null: false
      add :content, :text, null: false
      add :kind, :text, default: "chat"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :room_id,
          references(:mdt_rooms,
            column: :id,
            name: "mdt_messages_room_id_fkey",
            type: :uuid,
            prefix: prefix()
          ),
          null: false

      add :author_id,
          references(:users,
            column: :id,
            name: "mdt_messages_author_id_fkey",
            type: :uuid,
            prefix: prefix()
          )
    end

    create table(:mdt_conclusions, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :primary_diagnosis, :text
      add :differential, :text
      add :treatment, :text
      add :roles_considered, {:array, :text}, default: []
      add :summary, :text
      add :model, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :room_id,
          references(:mdt_rooms,
            column: :id,
            name: "mdt_conclusions_room_id_fkey",
            type: :uuid,
            prefix: prefix()
          ),
          null: false
    end

    create table(:mdt_cases, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:mdt_rooms, prefix: prefix()) do
      modify :case_id,
             references(:mdt_cases,
               column: :id,
               name: "mdt_rooms_case_id_fkey",
               type: :uuid,
               prefix: prefix()
             )

      modify :owner_id,
             references(:users,
               column: :id,
               name: "mdt_rooms_owner_id_fkey",
               type: :uuid,
               prefix: prefix()
             )
    end

    alter table(:mdt_cases, prefix: prefix()) do
      add :name, :text, null: false
      add :scenario_title, :text
      add :profile, :map, default: %{}
      add :complaint, :text, null: false
      add :history, :text
      add :departments, {:array, :text}, default: []
      add :expected_conclusion, :text
      add :status, :text, default: "draft"

      add :created_by_id,
          references(:users,
            column: :id,
            name: "mdt_cases_created_by_id_fkey",
            type: :uuid,
            prefix: prefix()
          ),
          null: false

      add :created_by_email, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    drop constraint(:mdt_cases, "mdt_cases_created_by_id_fkey")

    alter table(:mdt_cases, prefix: prefix()) do
      remove :updated_at
      remove :inserted_at
      remove :created_by_email
      remove :created_by_id
      remove :status
      remove :expected_conclusion
      remove :departments
      remove :history
      remove :complaint
      remove :profile
      remove :scenario_title
      remove :name
    end

    drop constraint(:mdt_rooms, "mdt_rooms_case_id_fkey")

    drop constraint(:mdt_rooms, "mdt_rooms_owner_id_fkey")

    alter table(:mdt_rooms, prefix: prefix()) do
      modify :owner_id, :uuid
      modify :case_id, :uuid
    end

    drop table(:mdt_cases, prefix: prefix())

    drop constraint(:mdt_conclusions, "mdt_conclusions_room_id_fkey")

    drop table(:mdt_conclusions, prefix: prefix())

    drop constraint(:mdt_messages, "mdt_messages_room_id_fkey")

    drop constraint(:mdt_messages, "mdt_messages_author_id_fkey")

    drop table(:mdt_messages, prefix: prefix())

    drop constraint(:mdt_participants, "mdt_participants_room_id_fkey")

    drop constraint(:mdt_participants, "mdt_participants_user_id_fkey")

    drop table(:mdt_participants, prefix: prefix())

    drop table(:mdt_rooms, prefix: prefix())
  end
end
