defmodule TcmEdu.Repo.TenantMigrations.AddExamModule do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:exams, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :description, :text
      add :subject, :text, default: "traditional_chinese_medicine"
      add :status, :text, default: "draft"
      add :source, :text, default: "manual"
      add :duration_minutes, :bigint, default: 60

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :created_by_id,
          references(:users,
            column: :id,
            name: "exams_created_by_id_fkey",
            type: :uuid,
            prefix: prefix()
          )
    end

    create table(:exam_responses, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :answer, :text
      add :is_correct, :boolean
      add :score, :decimal
      add :graded, :boolean, default: false
      add :comment, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :assignment_id, :uuid, null: false
      add :question_id, :uuid, null: false
    end

    create unique_index(:exam_responses, [:assignment_id, :question_id],
             name: "exam_responses_unique_assignment_question_index"
           )

    create table(:exam_questions, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :position, :bigint, default: 0
      add :score, :decimal, default: "10"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :exam_id,
          references(:exams,
            column: :id,
            name: "exam_questions_exam_id_fkey",
            type: :uuid,
            prefix: prefix()
          ),
          null: false

      add :question_id,
          references(:questions,
            column: :id,
            name: "exam_questions_question_id_fkey",
            type: :uuid,
            prefix: prefix()
          ),
          null: false
    end

    create unique_index(:exam_questions, [:exam_id, :question_id],
             name: "exam_questions_unique_exam_question_index"
           )

    create table(:exam_jobs, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :description, :text
      add :topic, :text
      add :subject, :text, default: "中医"
      add :question_count, :bigint, default: 5
      add :question_types, {:array, :text}
      add :difficulty, :bigint, default: 3
      add :knowledge_points, {:array, :text}, default: []
      add :total_score, :bigint, default: 100
      add :status, :text, default: "pending"
      add :error_message, :text
      add :oban_job_id, :bigint

      add :requested_by_id,
          references(:users,
            column: :id,
            name: "exam_jobs_requested_by_id_fkey",
            type: :uuid,
            prefix: prefix()
          ),
          null: false

      add :requested_by_email, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :started_at, :utc_datetime
      add :completed_at, :utc_datetime

      add :bank_id,
          references(:question_banks,
            column: :id,
            name: "exam_jobs_bank_id_fkey",
            type: :uuid,
            prefix: prefix()
          ),
          null: false

      add :exam_id,
          references(:exams,
            column: :id,
            name: "exam_jobs_exam_id_fkey",
            type: :uuid,
            prefix: prefix()
          )
    end

    create table(:exam_assignments, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:exam_responses, prefix: prefix()) do
      modify :assignment_id,
             references(:exam_assignments,
               column: :id,
               name: "exam_responses_assignment_id_fkey",
               type: :uuid,
               prefix: prefix()
             )

      modify :question_id,
             references(:questions,
               column: :id,
               name: "exam_responses_question_id_fkey",
               type: :uuid,
               prefix: prefix()
             )
    end

    alter table(:exam_assignments, prefix: prefix()) do
      add :status, :text, default: "assigned"
      add :assigned_at, :utc_datetime, default: fragment("(now() AT TIME ZONE 'utc')")
      add :started_at, :utc_datetime
      add :submitted_at, :utc_datetime
      add :graded_at, :utc_datetime
      add :objective_score, :decimal, default: "0"
      add :essay_score, :decimal, default: "0"
      add :total_score, :decimal, default: "0"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :exam_id,
          references(:exams,
            column: :id,
            name: "exam_assignments_exam_id_fkey",
            type: :uuid,
            prefix: prefix()
          ),
          null: false

      add :student_id,
          references(:users,
            column: :id,
            name: "exam_assignments_student_id_fkey",
            type: :uuid,
            prefix: prefix()
          ),
          null: false
    end

    create unique_index(:exam_assignments, [:exam_id, :student_id],
             name: "exam_assignments_unique_exam_student_index"
           )
  end

  def down do
    drop constraint(:exam_assignments, "exam_assignments_exam_id_fkey")

    drop constraint(:exam_assignments, "exam_assignments_student_id_fkey")

    drop_if_exists unique_index(:exam_assignments, [:exam_id, :student_id],
                     name: "exam_assignments_unique_exam_student_index"
                   )

    alter table(:exam_assignments, prefix: prefix()) do
      remove :student_id
      remove :exam_id
      remove :updated_at
      remove :inserted_at
      remove :total_score
      remove :essay_score
      remove :objective_score
      remove :graded_at
      remove :submitted_at
      remove :started_at
      remove :assigned_at
      remove :status
    end

    drop constraint(:exam_responses, "exam_responses_assignment_id_fkey")

    drop constraint(:exam_responses, "exam_responses_question_id_fkey")

    alter table(:exam_responses, prefix: prefix()) do
      modify :question_id, :uuid
      modify :assignment_id, :uuid
    end

    drop table(:exam_assignments, prefix: prefix())

    drop constraint(:exam_jobs, "exam_jobs_requested_by_id_fkey")

    drop constraint(:exam_jobs, "exam_jobs_bank_id_fkey")

    drop constraint(:exam_jobs, "exam_jobs_exam_id_fkey")

    drop table(:exam_jobs, prefix: prefix())

    drop constraint(:exam_questions, "exam_questions_exam_id_fkey")

    drop constraint(:exam_questions, "exam_questions_question_id_fkey")

    drop_if_exists unique_index(:exam_questions, [:exam_id, :question_id],
                     name: "exam_questions_unique_exam_question_index"
                   )

    drop table(:exam_questions, prefix: prefix())

    drop_if_exists unique_index(:exam_responses, [:assignment_id, :question_id],
                     name: "exam_responses_unique_assignment_question_index"
                   )

    drop table(:exam_responses, prefix: prefix())

    drop constraint(:exams, "exams_created_by_id_fkey")

    drop table(:exams, prefix: prefix())
  end
end
