defmodule TcmEdu.Repo.TenantMigrations.AddClassGroups do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users, prefix: prefix()) do
      add :student_no, :text
      add :class_group_id, :uuid
    end

    create table(:class_groups, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:users, prefix: prefix()) do
      modify :class_group_id,
             references(:class_groups,
               column: :id,
               name: "users_class_group_id_fkey",
               type: :uuid,
               prefix: prefix()
             )
    end

    alter table(:class_groups, prefix: prefix()) do
      add :name, :text, null: false
      add :grade_year, :bigint
      add :description, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:class_groups, [:name], name: "class_groups_unique_name_per_tenant_index")
  end

  def down do
    drop_if_exists unique_index(:class_groups, [:name],
                     name: "class_groups_unique_name_per_tenant_index"
                   )

    alter table(:class_groups, prefix: prefix()) do
      remove :updated_at
      remove :inserted_at
      remove :description
      remove :grade_year
      remove :name
    end

    drop constraint(:users, "users_class_group_id_fkey")

    alter table(:users, prefix: prefix()) do
      modify :class_group_id, :uuid
    end

    drop table(:class_groups, prefix: prefix())

    alter table(:users, prefix: prefix()) do
      remove :class_group_id
      remove :student_no
    end
  end
end
