defmodule TcmEdu.Repo.TenantMigrations.UpdateSpDefaults do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:simulated_patients, prefix: prefix()) do
      modify :max_turns, :bigint, default: 20
      modify :min_questions, :bigint, default: 5
    end
  end

  def down do
    alter table(:simulated_patients, prefix: prefix()) do
      modify :min_questions, :bigint, default: 8
      modify :max_turns, :bigint, default: 40
    end
  end
end
