defmodule TcmEdu.Repo.TenantMigrations.AddQuizJobs do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:quiz_jobs, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :topic, :text, null: false
      add :subject, :text, default: "中医"
      add :question_count, :bigint, default: 5
      add :question_types, {:array, :text}
      add :difficulty, :bigint, default: 3
      add :knowledge_points, {:array, :text}, default: []
      add :requirements, :text
      add :status, :text, default: "pending"
      add :generated_count, :bigint, default: 0
      add :question_ids, {:array, :text}, default: []
      add :error_message, :text
      add :oban_job_id, :bigint

      add :requested_by_id,
          references(:users,
            column: :id,
            name: "quiz_jobs_requested_by_id_fkey",
            type: :uuid,
            prefix: prefix()
          ),
          null: false

      add :requested_by_email, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :started_at, :utc_datetime
      add :completed_at, :utc_datetime

      add :bank_id,
          references(:question_banks,
            column: :id,
            name: "quiz_jobs_bank_id_fkey",
            type: :uuid,
            prefix: prefix()
          ),
          null: false
    end
  end

  def down do
    drop constraint(:quiz_jobs, "quiz_jobs_requested_by_id_fkey")

    drop constraint(:quiz_jobs, "quiz_jobs_bank_id_fkey")

    drop table(:quiz_jobs, prefix: prefix())
  end
end
