// Generated by AshTypescript - Shared Zod Schemas
// Do not edit this file manually

import { z } from "zod";



export const changeUserPasswordSchema = z.object({
  currentPassword: z.string().min(1),
  password: z.string().min(8),
  passwordConfirmation: z.string().min(1),
});

export const registerWithRoleSchema = z.object({
  email: z.string().min(1),
  name: z.string().nullable().optional(),
  phone: z.string().nullable().optional(),
  avatarUrl: z.string().nullable().optional(),
  role: z.enum(["student", "teacher", "tenant_admin"]).optional(),
  status: z.enum(["active", "disabled"]).optional(),
  password: z.string().min(8),
});

export const updateProfileSchema = z.object({
  name: z.string().nullable().optional(),
  avatarUrl: z.string().nullable().optional(),
  phone: z.string().nullable().optional(),
  bio: z.string().nullable().optional(),
  jobTitle: z.string().nullable().optional(),
  school: z.string().nullable().optional(),
  major: z.string().nullable().optional(),
});

export const updateUserRoleSchema = z.object({
  role: z.enum(["student", "teacher", "tenant_admin"]),
});

export const updateUserStatusSchema = z.object({
  status: z.enum(["active", "disabled"]),
});

export const createMessageSchema = z.object({
  sessionId: z.string().min(1),
  role: z.string().min(1),
  content: z.string().min(1),
});

export const createSessionSchema = z.object({
  userId: z.uuid(),
  agentName: z.string().min(1),
  title: z.string().min(1).optional(),
});

export const getTaskSchema = z.object({
  taskId: z.string().min(1),
});

export const createChapterSchema = z.object({
  title: z.string().min(1),
  sortOrder: z.number().int().nullable().optional(),
  courseId: z.uuid(),
});

export const updateChapterSchema = z.object({
  title: z.string().min(1).optional(),
  sortOrder: z.number().int().nullable().optional(),
});

export const createCourseSchema = z.object({
  title: z.string().min(1),
  subtitle: z.string().nullable().optional(),
  description: z.string().nullable().optional(),
  coverImageUrl: z.string().nullable().optional(),
  tags: z.array(z.string()).nullable().optional(),
  level: z.enum(["advanced", "beginner", "intermediate"]).nullable().optional(),
  priceCents: z.number().int().nullable().optional(),
  teacherId: z.uuid(),
  categoryId: z.uuid().nullable().optional(),
});

export const listCategoryCoursesSchema = z.object({
  categoryId: z.uuid(),
});

export const listTeacherCoursesSchema = z.object({
  teacherId: z.uuid(),
});

export const updateCourseSchema = z.object({
  title: z.string().min(1).optional(),
  subtitle: z.string().nullable().optional(),
  description: z.string().nullable().optional(),
  coverImageUrl: z.string().nullable().optional(),
  tags: z.array(z.string()).nullable().optional(),
  level: z.enum(["advanced", "beginner", "intermediate"]).nullable().optional(),
  priceCents: z.number().int().nullable().optional(),
  categoryId: z.uuid().nullable().optional(),
});

export const createCategorySchema = z.object({
  name: z.string().min(1),
  slug: z.string().min(1).regex(/^[a-z0-9][a-z0-9-]{1,30}[a-z0-9]$/),
  icon: z.string().nullable().optional(),
  sortOrder: z.number().int().nullable().optional(),
  parentId: z.uuid().nullable().optional(),
});

export const createLessonSchema = z.object({
  title: z.string().min(1),
  contentType: z.enum(["article", "pdf", "video"]).nullable().optional(),
  contentUrl: z.string().nullable().optional(),
  contentText: z.string().nullable().optional(),
  durationSeconds: z.number().int().nullable().optional(),
  sortOrder: z.number().int().nullable().optional(),
  isFreePreview: z.boolean().nullable().optional(),
  chapterId: z.uuid(),
});

export const updateLessonSchema = z.object({
  title: z.string().min(1).optional(),
  contentType: z.enum(["article", "pdf", "video"]).nullable().optional(),
  contentUrl: z.string().nullable().optional(),
  contentText: z.string().nullable().optional(),
  durationSeconds: z.number().int().nullable().optional(),
  sortOrder: z.number().int().nullable().optional(),
  isFreePreview: z.boolean().nullable().optional(),
});

export const enrollInCourseSchema = z.object({
  courseId: z.uuid(),
});

export const updateProgressSchema = z.object({
  status: z.enum(["completed", "in_progress", "not_started"]).nullable().optional(),
  progressPct: z.number().int().min(0).max(100).nullable().optional(),
  lastPositionSeconds: z.number().int().nullable().optional(),
});

export const upsertProgressSchema = z.object({
  enrollmentId: z.uuid(),
  lessonId: z.uuid(),
  status: z.enum(["completed", "in_progress", "not_started"]).nullable().optional(),
  progressPct: z.number().int().min(0).max(100).nullable().optional(),
  lastPositionSeconds: z.number().int().nullable().optional(),
});

export const createPostSchema = z.object({
  title: z.string().min(1).max(200),
  body: z.string().max(10000).nullable().optional(),
});

export const updatePostSchema = z.object({
  title: z.string().min(1).max(200).optional(),
  body: z.string().max(10000).nullable().optional(),
});

export const createOrganizationSchema = z.object({
  name: z.string().min(1),
  slug: z.string().min(1).regex(/^[a-z0-9][a-z0-9-]{1,30}[a-z0-9]$/),
  contactEmail: z.string().nullable().optional(),
  contactPhone: z.string().nullable().optional(),
  description: z.string().nullable().optional(),
  logoUrl: z.string().nullable().optional(),
  plan: z.enum(["enterprise", "free", "pro"]).nullable().optional(),
  expiresAt: z.iso.datetime().nullable().optional(),
});

export const updateOrganizationSchema = z.object({
  name: z.string().min(1).optional(),
  contactEmail: z.string().nullable().optional(),
  contactPhone: z.string().nullable().optional(),
  description: z.string().nullable().optional(),
  logoUrl: z.string().nullable().optional(),
  plan: z.enum(["enterprise", "free", "pro"]).nullable().optional(),
  expiresAt: z.iso.datetime().nullable().optional(),
});

export const registerSuperAdminSchema = z.object({
  email: z.string().min(1),
  name: z.string().nullable().optional(),
  password: z.string().min(8),
});

export const superAdminSignInSchema = z.object({
  email: z.string().min(1),
  password: z.string().min(1),
});

export const createTodoSchema = z.object({
  title: z.string().min(1).max(200),
  completed: z.boolean().optional(),
});

export const updateTodoSchema = z.object({
  title: z.string().min(1).max(200).optional(),
  completed: z.boolean().optional(),
});

