// Generated by AshTypescript - Shared Types
// Do not edit this file manually

import * as RpcHooks from "./rpcHooks";

export type Decimal = string;
export type UUID = string;
export type UtcDateTime = string;
export type UtcDateTimeUsec = string;

// User Schema
export type UserResourceSchema = {
  __type: "Resource";
  __primitiveFields: "id" | "email" | "name" | "avatarUrl" | "phone" | "bio" | "jobTitle" | "school" | "major" | "role" | "status";
  id: UUID;
  email: string;
  name: string | null;
  avatarUrl: string | null;
  phone: string | null;
  bio: string | null;
  jobTitle: string | null;
  school: string | null;
  major: string | null;
  role: "student" | "teacher" | "tenant_admin";
  status: "active" | "disabled";
};



export type UserAttributesOnlySchema = {
  __type: "Resource";
  __primitiveFields: "id" | "email" | "name" | "avatarUrl" | "phone" | "bio" | "jobTitle" | "school" | "major" | "role" | "status";
  id: UUID;
  email: string;
  name: string | null;
  avatarUrl: string | null;
  phone: string | null;
  bio: string | null;
  jobTitle: string | null;
  school: string | null;
  major: string | null;
  role: "student" | "teacher" | "tenant_admin";
  status: "active" | "disabled";
};


// ChatMessage Schema
export type ChatMessageResourceSchema = {
  __type: "Resource";
  __primitiveFields: "id" | "sessionId" | "role" | "content" | "insertedAt";
  id: UUID;
  sessionId: string;
  role: string;
  content: string;
  insertedAt: UtcDateTimeUsec;
};



export type ChatMessageAttributesOnlySchema = {
  __type: "Resource";
  __primitiveFields: "id" | "sessionId" | "role" | "content" | "insertedAt";
  id: UUID;
  sessionId: string;
  role: string;
  content: string;
  insertedAt: UtcDateTimeUsec;
};


// ChatSession Schema
export type ChatSessionResourceSchema = {
  __type: "Resource";
  __primitiveFields: "id" | "userId" | "agentName" | "title" | "insertedAt" | "updatedAt";
  id: UUID;
  userId: UUID;
  agentName: string;
  title: string;
  insertedAt: UtcDateTimeUsec;
  updatedAt: UtcDateTimeUsec;
};



export type ChatSessionAttributesOnlySchema = {
  __type: "Resource";
  __primitiveFields: "id" | "userId" | "agentName" | "title" | "insertedAt" | "updatedAt";
  id: UUID;
  userId: UUID;
  agentName: string;
  title: string;
  insertedAt: UtcDateTimeUsec;
  updatedAt: UtcDateTimeUsec;
};


// ChatTask Schema
export type ChatTaskResourceSchema = {
  __type: "Resource";
  __primitiveFields: "id" | "taskId" | "userId" | "sessionId" | "agentName" | "taskName" | "durationMs" | "status" | "jobId" | "result" | "errorMessage" | "insertedAt" | "updatedAt" | "startedAt" | "completedAt";
  id: UUID;
  taskId: string;
  userId: UUID;
  sessionId: string;
  agentName: string;
  taskName: string;
  durationMs: number;
  status: "completed" | "failed" | "pending" | "running";
  jobId: number | null;
  result: Record<string, any> | null;
  errorMessage: string | null;
  insertedAt: UtcDateTimeUsec;
  updatedAt: UtcDateTimeUsec;
  startedAt: UtcDateTime | null;
  completedAt: UtcDateTime | null;
};



export type ChatTaskAttributesOnlySchema = {
  __type: "Resource";
  __primitiveFields: "id" | "taskId" | "userId" | "sessionId" | "agentName" | "taskName" | "durationMs" | "status" | "jobId" | "result" | "errorMessage" | "insertedAt" | "updatedAt" | "startedAt" | "completedAt";
  id: UUID;
  taskId: string;
  userId: UUID;
  sessionId: string;
  agentName: string;
  taskName: string;
  durationMs: number;
  status: "completed" | "failed" | "pending" | "running";
  jobId: number | null;
  result: Record<string, any> | null;
  errorMessage: string | null;
  insertedAt: UtcDateTimeUsec;
  updatedAt: UtcDateTimeUsec;
  startedAt: UtcDateTime | null;
  completedAt: UtcDateTime | null;
};


// Chapter Schema
export type ChapterResourceSchema = {
  __type: "Resource";
  __primitiveFields: "id" | "title" | "sortOrder" | "courseId";
  id: UUID;
  title: string;
  sortOrder: number | null;
  courseId: UUID;
  course: { __type: "Relationship"; __resource: CourseResourceSchema; };
  lessons: { __type: "Relationship"; __array: true; __resource: LessonResourceSchema; };
};



export type ChapterAttributesOnlySchema = {
  __type: "Resource";
  __primitiveFields: "id" | "title" | "sortOrder" | "courseId";
  id: UUID;
  title: string;
  sortOrder: number | null;
  courseId: UUID;
};


// Course Schema
export type CourseResourceSchema = {
  __type: "Resource";
  __primitiveFields: "id" | "title" | "subtitle" | "description" | "coverImageUrl" | "tags" | "level" | "status" | "priceCents" | "publishedAt" | "teacherId" | "categoryId" | "lessonCount" | "durationSeconds";
  id: UUID;
  title: string;
  subtitle: string | null;
  description: string | null;
  coverImageUrl: string | null;
  tags: Array<string> | null;
  level: "advanced" | "beginner" | "intermediate" | null;
  status: "archived" | "draft" | "published" | null;
  priceCents: number | null;
  publishedAt: UtcDateTime | null;
  teacherId: UUID;
  categoryId: UUID | null;
  lessonCount: number | null;
  durationSeconds: Decimal | null;
  teacher: { __type: "Relationship"; __resource: UserResourceSchema; };
  category: { __type: "Relationship"; __resource: CourseCategoryResourceSchema | null; };
  chapters: { __type: "Relationship"; __array: true; __resource: ChapterResourceSchema; };
};



export type CourseAttributesOnlySchema = {
  __type: "Resource";
  __primitiveFields: "id" | "title" | "subtitle" | "description" | "coverImageUrl" | "tags" | "level" | "status" | "priceCents" | "publishedAt" | "teacherId" | "categoryId";
  id: UUID;
  title: string;
  subtitle: string | null;
  description: string | null;
  coverImageUrl: string | null;
  tags: Array<string> | null;
  level: "advanced" | "beginner" | "intermediate" | null;
  status: "archived" | "draft" | "published" | null;
  priceCents: number | null;
  publishedAt: UtcDateTime | null;
  teacherId: UUID;
  categoryId: UUID | null;
};


// CourseCategory Schema
export type CourseCategoryResourceSchema = {
  __type: "Resource";
  __primitiveFields: "id" | "name" | "slug" | "icon" | "sortOrder";
  id: UUID;
  name: string;
  slug: string;
  icon: string | null;
  sortOrder: number | null;
};



export type CourseCategoryAttributesOnlySchema = {
  __type: "Resource";
  __primitiveFields: "id" | "name" | "slug" | "icon" | "sortOrder";
  id: UUID;
  name: string;
  slug: string;
  icon: string | null;
  sortOrder: number | null;
};


// Lesson Schema
export type LessonResourceSchema = {
  __type: "Resource";
  __primitiveFields: "id" | "title" | "contentType" | "contentUrl" | "contentText" | "durationSeconds" | "sortOrder" | "isFreePreview" | "chapterId";
  id: UUID;
  title: string;
  contentType: "article" | "pdf" | "video" | null;
  contentUrl: string | null;
  contentText: string | null;
  durationSeconds: number | null;
  sortOrder: number | null;
  isFreePreview: boolean | null;
  chapterId: UUID;
  chapter: { __type: "Relationship"; __resource: ChapterResourceSchema; };
};



export type LessonAttributesOnlySchema = {
  __type: "Resource";
  __primitiveFields: "id" | "title" | "contentType" | "contentUrl" | "contentText" | "durationSeconds" | "sortOrder" | "isFreePreview" | "chapterId";
  id: UUID;
  title: string;
  contentType: "article" | "pdf" | "video" | null;
  contentUrl: string | null;
  contentText: string | null;
  durationSeconds: number | null;
  sortOrder: number | null;
  isFreePreview: boolean | null;
  chapterId: UUID;
};


// Post Schema
export type PostResourceSchema = {
  __type: "Resource";
  __primitiveFields: "id" | "title" | "body" | "insertedAt" | "updatedAt" | "coverImageUrl" | "attachmentsUrls" | "attachmentsThumbnailUrls";
  id: UUID;
  title: string;
  body: string | null;
  insertedAt: UtcDateTimeUsec;
  updatedAt: UtcDateTimeUsec;
  coverImageUrl: string | null;
  attachmentsUrls: Array<string> | null;
  attachmentsThumbnailUrls: Array<string> | null;
};



export type PostAttributesOnlySchema = {
  __type: "Resource";
  __primitiveFields: "id" | "title" | "body" | "insertedAt" | "updatedAt";
  id: UUID;
  title: string;
  body: string | null;
  insertedAt: UtcDateTimeUsec;
  updatedAt: UtcDateTimeUsec;
};


// Organization Schema
export type OrganizationResourceSchema = {
  __type: "Resource";
  __primitiveFields: "id" | "name" | "slug" | "schemaName" | "contactEmail" | "contactPhone" | "description" | "logoUrl" | "status" | "plan" | "expiresAt";
  id: UUID;
  name: string;
  slug: string;
  schemaName: string | null;
  contactEmail: string | null;
  contactPhone: string | null;
  description: string | null;
  logoUrl: string | null;
  status: "active" | "archived" | "suspended" | null;
  plan: "enterprise" | "free" | "pro" | null;
  expiresAt: UtcDateTime | null;
};



export type OrganizationAttributesOnlySchema = {
  __type: "Resource";
  __primitiveFields: "id" | "name" | "slug" | "schemaName" | "contactEmail" | "contactPhone" | "description" | "logoUrl" | "status" | "plan" | "expiresAt";
  id: UUID;
  name: string;
  slug: string;
  schemaName: string | null;
  contactEmail: string | null;
  contactPhone: string | null;
  description: string | null;
  logoUrl: string | null;
  status: "active" | "archived" | "suspended" | null;
  plan: "enterprise" | "free" | "pro" | null;
  expiresAt: UtcDateTime | null;
};


// SuperAdmin Schema
export type SuperAdminResourceSchema = {
  __type: "Resource";
  __primitiveFields: "id" | "email" | "name" | "lastLoginAt";
  id: UUID;
  email: string;
  name: string | null;
  lastLoginAt: UtcDateTime | null;
};



export type SuperAdminAttributesOnlySchema = {
  __type: "Resource";
  __primitiveFields: "id" | "email" | "name" | "lastLoginAt";
  id: UUID;
  email: string;
  name: string | null;
  lastLoginAt: UtcDateTime | null;
};


// Todo Schema
export type TodoResourceSchema = {
  __type: "Resource";
  __primitiveFields: "id" | "title" | "completed" | "insertedAt" | "updatedAt";
  id: UUID;
  title: string;
  completed: boolean;
  insertedAt: UtcDateTimeUsec;
  updatedAt: UtcDateTimeUsec;
};



export type TodoAttributesOnlySchema = {
  __type: "Resource";
  __primitiveFields: "id" | "title" | "completed" | "insertedAt" | "updatedAt";
  id: UUID;
  title: string;
  completed: boolean;
  insertedAt: UtcDateTimeUsec;
  updatedAt: UtcDateTimeUsec;
};


export type UserFilterInput = {
  and?: Array<UserFilterInput>;
  or?: Array<UserFilterInput>;
  not?: Array<UserFilterInput>;

  id?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
  };

  email?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
  };

  name?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
    isNil?: boolean;
  };

  avatarUrl?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
    isNil?: boolean;
  };

  phone?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
    isNil?: boolean;
  };

  bio?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
    isNil?: boolean;
  };

  jobTitle?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
    isNil?: boolean;
  };

  school?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
    isNil?: boolean;
  };

  major?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
    isNil?: boolean;
  };

  role?: {
    eq?: "student" | "teacher" | "tenant_admin";
    notEq?: "student" | "teacher" | "tenant_admin";
    in?: Array<"student" | "teacher" | "tenant_admin">;
  };

  status?: {
    eq?: "active" | "disabled";
    notEq?: "active" | "disabled";
    in?: Array<"active" | "disabled">;
  };



};
export type ChatMessageFilterInput = {
  and?: Array<ChatMessageFilterInput>;
  or?: Array<ChatMessageFilterInput>;
  not?: Array<ChatMessageFilterInput>;

  id?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
  };

  sessionId?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
  };

  role?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
  };

  content?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
  };

  insertedAt?: {
    eq?: UtcDateTimeUsec;
    notEq?: UtcDateTimeUsec;
    greaterThan?: UtcDateTimeUsec;
    greaterThanOrEqual?: UtcDateTimeUsec;
    lessThan?: UtcDateTimeUsec;
    lessThanOrEqual?: UtcDateTimeUsec;
    in?: Array<UtcDateTimeUsec>;
  };



};
export type ChatSessionFilterInput = {
  and?: Array<ChatSessionFilterInput>;
  or?: Array<ChatSessionFilterInput>;
  not?: Array<ChatSessionFilterInput>;

  id?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
  };

  userId?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
  };

  agentName?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
  };

  title?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
  };

  insertedAt?: {
    eq?: UtcDateTimeUsec;
    notEq?: UtcDateTimeUsec;
    greaterThan?: UtcDateTimeUsec;
    greaterThanOrEqual?: UtcDateTimeUsec;
    lessThan?: UtcDateTimeUsec;
    lessThanOrEqual?: UtcDateTimeUsec;
    in?: Array<UtcDateTimeUsec>;
  };

  updatedAt?: {
    eq?: UtcDateTimeUsec;
    notEq?: UtcDateTimeUsec;
    greaterThan?: UtcDateTimeUsec;
    greaterThanOrEqual?: UtcDateTimeUsec;
    lessThan?: UtcDateTimeUsec;
    lessThanOrEqual?: UtcDateTimeUsec;
    in?: Array<UtcDateTimeUsec>;
  };



};
export type ChatTaskFilterInput = {
  and?: Array<ChatTaskFilterInput>;
  or?: Array<ChatTaskFilterInput>;
  not?: Array<ChatTaskFilterInput>;

  id?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
  };

  taskId?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
  };

  userId?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
  };

  sessionId?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
  };

  agentName?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
  };

  taskName?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
  };

  durationMs?: {
    eq?: number;
    notEq?: number;
    greaterThan?: number;
    greaterThanOrEqual?: number;
    lessThan?: number;
    lessThanOrEqual?: number;
    in?: Array<number>;
  };

  status?: {
    eq?: "completed" | "failed" | "pending" | "running";
    notEq?: "completed" | "failed" | "pending" | "running";
    in?: Array<"completed" | "failed" | "pending" | "running">;
  };

  jobId?: {
    eq?: number;
    notEq?: number;
    greaterThan?: number;
    greaterThanOrEqual?: number;
    lessThan?: number;
    lessThanOrEqual?: number;
    in?: Array<number>;
    isNil?: boolean;
  };

  result?: {
    eq?: Record<string, any>;
    notEq?: Record<string, any>;
    in?: Array<Record<string, any>>;
    isNil?: boolean;
  };

  errorMessage?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
    isNil?: boolean;
  };

  insertedAt?: {
    eq?: UtcDateTimeUsec;
    notEq?: UtcDateTimeUsec;
    greaterThan?: UtcDateTimeUsec;
    greaterThanOrEqual?: UtcDateTimeUsec;
    lessThan?: UtcDateTimeUsec;
    lessThanOrEqual?: UtcDateTimeUsec;
    in?: Array<UtcDateTimeUsec>;
  };

  updatedAt?: {
    eq?: UtcDateTimeUsec;
    notEq?: UtcDateTimeUsec;
    greaterThan?: UtcDateTimeUsec;
    greaterThanOrEqual?: UtcDateTimeUsec;
    lessThan?: UtcDateTimeUsec;
    lessThanOrEqual?: UtcDateTimeUsec;
    in?: Array<UtcDateTimeUsec>;
  };

  startedAt?: {
    eq?: UtcDateTime;
    notEq?: UtcDateTime;
    greaterThan?: UtcDateTime;
    greaterThanOrEqual?: UtcDateTime;
    lessThan?: UtcDateTime;
    lessThanOrEqual?: UtcDateTime;
    in?: Array<UtcDateTime>;
    isNil?: boolean;
  };

  completedAt?: {
    eq?: UtcDateTime;
    notEq?: UtcDateTime;
    greaterThan?: UtcDateTime;
    greaterThanOrEqual?: UtcDateTime;
    lessThan?: UtcDateTime;
    lessThanOrEqual?: UtcDateTime;
    in?: Array<UtcDateTime>;
    isNil?: boolean;
  };



};
export type ChapterFilterInput = {
  and?: Array<ChapterFilterInput>;
  or?: Array<ChapterFilterInput>;
  not?: Array<ChapterFilterInput>;

  id?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
  };

  title?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
  };

  sortOrder?: {
    eq?: number;
    notEq?: number;
    greaterThan?: number;
    greaterThanOrEqual?: number;
    lessThan?: number;
    lessThanOrEqual?: number;
    in?: Array<number>;
    isNil?: boolean;
  };

  courseId?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
  };


  course?: CourseFilterInput;

  lessons?: LessonFilterInput;

};
export type CourseFilterInput = {
  and?: Array<CourseFilterInput>;
  or?: Array<CourseFilterInput>;
  not?: Array<CourseFilterInput>;

  id?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
  };

  title?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
  };

  subtitle?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
    isNil?: boolean;
  };

  description?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
    isNil?: boolean;
  };

  coverImageUrl?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
    isNil?: boolean;
  };

  tags?: {
    eq?: Array<string>;
    notEq?: Array<string>;
    in?: Array<Array<string>>;
    isNil?: boolean;
  };

  level?: {
    eq?: "advanced" | "beginner" | "intermediate";
    notEq?: "advanced" | "beginner" | "intermediate";
    in?: Array<"advanced" | "beginner" | "intermediate">;
    isNil?: boolean;
  };

  status?: {
    eq?: "archived" | "draft" | "published";
    notEq?: "archived" | "draft" | "published";
    in?: Array<"archived" | "draft" | "published">;
    isNil?: boolean;
  };

  priceCents?: {
    eq?: number;
    notEq?: number;
    greaterThan?: number;
    greaterThanOrEqual?: number;
    lessThan?: number;
    lessThanOrEqual?: number;
    in?: Array<number>;
    isNil?: boolean;
  };

  publishedAt?: {
    eq?: UtcDateTime;
    notEq?: UtcDateTime;
    greaterThan?: UtcDateTime;
    greaterThanOrEqual?: UtcDateTime;
    lessThan?: UtcDateTime;
    lessThanOrEqual?: UtcDateTime;
    in?: Array<UtcDateTime>;
    isNil?: boolean;
  };

  teacherId?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
  };

  categoryId?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
    isNil?: boolean;
  };

  lessonCount?: {
    eq?: number;
    notEq?: number;
    greaterThan?: number;
    greaterThanOrEqual?: number;
    lessThan?: number;
    lessThanOrEqual?: number;
    in?: Array<number>;
    isNil?: boolean;
  };

  durationSeconds?: {
    eq?: Decimal;
    notEq?: Decimal;
    greaterThan?: Decimal;
    greaterThanOrEqual?: Decimal;
    lessThan?: Decimal;
    lessThanOrEqual?: Decimal;
    in?: Array<Decimal>;
    isNil?: boolean;
  };


  teacher?: UserFilterInput;

  category?: CourseCategoryFilterInput;

  chapters?: ChapterFilterInput;

};
export type CourseCategoryFilterInput = {
  and?: Array<CourseCategoryFilterInput>;
  or?: Array<CourseCategoryFilterInput>;
  not?: Array<CourseCategoryFilterInput>;

  id?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
  };

  name?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
  };

  slug?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
  };

  icon?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
    isNil?: boolean;
  };

  sortOrder?: {
    eq?: number;
    notEq?: number;
    greaterThan?: number;
    greaterThanOrEqual?: number;
    lessThan?: number;
    lessThanOrEqual?: number;
    in?: Array<number>;
    isNil?: boolean;
  };



};
export type LessonFilterInput = {
  and?: Array<LessonFilterInput>;
  or?: Array<LessonFilterInput>;
  not?: Array<LessonFilterInput>;

  id?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
  };

  title?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
  };

  contentType?: {
    eq?: "article" | "pdf" | "video";
    notEq?: "article" | "pdf" | "video";
    in?: Array<"article" | "pdf" | "video">;
    isNil?: boolean;
  };

  contentUrl?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
    isNil?: boolean;
  };

  contentText?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
    isNil?: boolean;
  };

  durationSeconds?: {
    eq?: number;
    notEq?: number;
    greaterThan?: number;
    greaterThanOrEqual?: number;
    lessThan?: number;
    lessThanOrEqual?: number;
    in?: Array<number>;
    isNil?: boolean;
  };

  sortOrder?: {
    eq?: number;
    notEq?: number;
    greaterThan?: number;
    greaterThanOrEqual?: number;
    lessThan?: number;
    lessThanOrEqual?: number;
    in?: Array<number>;
    isNil?: boolean;
  };

  isFreePreview?: {
    eq?: boolean;
    notEq?: boolean;
    isNil?: boolean;
  };

  chapterId?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
  };


  chapter?: ChapterFilterInput;

};
export type PostFilterInput = {
  and?: Array<PostFilterInput>;
  or?: Array<PostFilterInput>;
  not?: Array<PostFilterInput>;

  id?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
  };

  title?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
  };

  body?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
    isNil?: boolean;
  };

  insertedAt?: {
    eq?: UtcDateTimeUsec;
    notEq?: UtcDateTimeUsec;
    greaterThan?: UtcDateTimeUsec;
    greaterThanOrEqual?: UtcDateTimeUsec;
    lessThan?: UtcDateTimeUsec;
    lessThanOrEqual?: UtcDateTimeUsec;
    in?: Array<UtcDateTimeUsec>;
  };

  updatedAt?: {
    eq?: UtcDateTimeUsec;
    notEq?: UtcDateTimeUsec;
    greaterThan?: UtcDateTimeUsec;
    greaterThanOrEqual?: UtcDateTimeUsec;
    lessThan?: UtcDateTimeUsec;
    lessThanOrEqual?: UtcDateTimeUsec;
    in?: Array<UtcDateTimeUsec>;
  };

  coverImageUrl?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
    isNil?: boolean;
  };

  attachmentsUrls?: {
    eq?: Array<string>;
    notEq?: Array<string>;
    in?: Array<Array<string>>;
    isNil?: boolean;
  };

  attachmentsThumbnailUrls?: {
    eq?: Array<string>;
    notEq?: Array<string>;
    in?: Array<Array<string>>;
    isNil?: boolean;
  };



};
export type OrganizationFilterInput = {
  and?: Array<OrganizationFilterInput>;
  or?: Array<OrganizationFilterInput>;
  not?: Array<OrganizationFilterInput>;

  id?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
  };

  name?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
  };

  slug?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
  };

  schemaName?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
    isNil?: boolean;
  };

  contactEmail?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
    isNil?: boolean;
  };

  contactPhone?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
    isNil?: boolean;
  };

  description?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
    isNil?: boolean;
  };

  logoUrl?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
    isNil?: boolean;
  };

  status?: {
    eq?: "active" | "archived" | "suspended";
    notEq?: "active" | "archived" | "suspended";
    in?: Array<"active" | "archived" | "suspended">;
    isNil?: boolean;
  };

  plan?: {
    eq?: "enterprise" | "free" | "pro";
    notEq?: "enterprise" | "free" | "pro";
    in?: Array<"enterprise" | "free" | "pro">;
    isNil?: boolean;
  };

  expiresAt?: {
    eq?: UtcDateTime;
    notEq?: UtcDateTime;
    greaterThan?: UtcDateTime;
    greaterThanOrEqual?: UtcDateTime;
    lessThan?: UtcDateTime;
    lessThanOrEqual?: UtcDateTime;
    in?: Array<UtcDateTime>;
    isNil?: boolean;
  };



};
export type SuperAdminFilterInput = {
  and?: Array<SuperAdminFilterInput>;
  or?: Array<SuperAdminFilterInput>;
  not?: Array<SuperAdminFilterInput>;

  id?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
  };

  email?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
  };

  name?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
    isNil?: boolean;
  };

  lastLoginAt?: {
    eq?: UtcDateTime;
    notEq?: UtcDateTime;
    greaterThan?: UtcDateTime;
    greaterThanOrEqual?: UtcDateTime;
    lessThan?: UtcDateTime;
    lessThanOrEqual?: UtcDateTime;
    in?: Array<UtcDateTime>;
    isNil?: boolean;
  };



};
export type TodoFilterInput = {
  and?: Array<TodoFilterInput>;
  or?: Array<TodoFilterInput>;
  not?: Array<TodoFilterInput>;

  id?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
  };

  title?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
  };

  completed?: {
    eq?: boolean;
    notEq?: boolean;
  };

  insertedAt?: {
    eq?: UtcDateTimeUsec;
    notEq?: UtcDateTimeUsec;
    greaterThan?: UtcDateTimeUsec;
    greaterThanOrEqual?: UtcDateTimeUsec;
    lessThan?: UtcDateTimeUsec;
    lessThanOrEqual?: UtcDateTimeUsec;
    in?: Array<UtcDateTimeUsec>;
  };

  updatedAt?: {
    eq?: UtcDateTimeUsec;
    notEq?: UtcDateTimeUsec;
    greaterThan?: UtcDateTimeUsec;
    greaterThanOrEqual?: UtcDateTimeUsec;
    lessThan?: UtcDateTimeUsec;
    lessThanOrEqual?: UtcDateTimeUsec;
    in?: Array<UtcDateTimeUsec>;
  };



};


export const userFilterFields = ["id", "email", "name", "avatarUrl", "phone", "bio", "jobTitle", "school", "major", "role", "status"] as const;
export type UserFilterField = (typeof userFilterFields)[number];

export const chatMessageFilterFields = ["id", "sessionId", "role", "content", "insertedAt"] as const;
export type ChatMessageFilterField = (typeof chatMessageFilterFields)[number];

export const chatSessionFilterFields = ["id", "userId", "agentName", "title", "insertedAt", "updatedAt"] as const;
export type ChatSessionFilterField = (typeof chatSessionFilterFields)[number];

export const chatTaskFilterFields = ["id", "taskId", "userId", "sessionId", "agentName", "taskName", "durationMs", "status", "jobId", "result", "errorMessage", "insertedAt", "updatedAt", "startedAt", "completedAt"] as const;
export type ChatTaskFilterField = (typeof chatTaskFilterFields)[number];

export const chapterFilterFields = ["id", "title", "sortOrder", "courseId", "course", "lessons"] as const;
export type ChapterFilterField = (typeof chapterFilterFields)[number];

export const courseFilterFields = ["id", "title", "subtitle", "description", "coverImageUrl", "tags", "level", "status", "priceCents", "publishedAt", "teacherId", "categoryId", "lessonCount", "durationSeconds", "teacher", "category", "chapters"] as const;
export type CourseFilterField = (typeof courseFilterFields)[number];

export const courseCategoryFilterFields = ["id", "name", "slug", "icon", "sortOrder"] as const;
export type CourseCategoryFilterField = (typeof courseCategoryFilterFields)[number];

export const lessonFilterFields = ["id", "title", "contentType", "contentUrl", "contentText", "durationSeconds", "sortOrder", "isFreePreview", "chapterId", "chapter"] as const;
export type LessonFilterField = (typeof lessonFilterFields)[number];

export const postFilterFields = ["id", "title", "body", "insertedAt", "updatedAt", "coverImageUrl", "attachmentsUrls", "attachmentsThumbnailUrls", "coverImage", "attachments"] as const;
export type PostFilterField = (typeof postFilterFields)[number];

export const organizationFilterFields = ["id", "name", "slug", "schemaName", "contactEmail", "contactPhone", "description", "logoUrl", "status", "plan", "expiresAt"] as const;
export type OrganizationFilterField = (typeof organizationFilterFields)[number];

export const superAdminFilterFields = ["id", "email", "name", "lastLoginAt"] as const;
export type SuperAdminFilterField = (typeof superAdminFilterFields)[number];

export const todoFilterFields = ["id", "title", "completed", "insertedAt", "updatedAt"] as const;
export type TodoFilterField = (typeof todoFilterFields)[number];


export const userSortFields = ["id", "email", "name", "avatarUrl", "phone", "bio", "jobTitle", "school", "major", "role", "status"] as const;
export type UserSortField = (typeof userSortFields)[number];

export const chatMessageSortFields = ["id", "sessionId", "role", "content", "insertedAt"] as const;
export type ChatMessageSortField = (typeof chatMessageSortFields)[number];

export const chatSessionSortFields = ["id", "userId", "agentName", "title", "insertedAt", "updatedAt"] as const;
export type ChatSessionSortField = (typeof chatSessionSortFields)[number];

export const chatTaskSortFields = ["id", "taskId", "userId", "sessionId", "agentName", "taskName", "durationMs", "status", "jobId", "result", "errorMessage", "insertedAt", "updatedAt", "startedAt", "completedAt"] as const;
export type ChatTaskSortField = (typeof chatTaskSortFields)[number];

export const chapterSortFields = ["id", "title", "sortOrder", "courseId"] as const;
export type ChapterSortField = (typeof chapterSortFields)[number];

export const courseSortFields = ["id", "title", "subtitle", "description", "coverImageUrl", "tags", "level", "status", "priceCents", "publishedAt", "teacherId", "categoryId", "lessonCount", "durationSeconds"] as const;
export type CourseSortField = (typeof courseSortFields)[number];

export const courseCategorySortFields = ["id", "name", "slug", "icon", "sortOrder"] as const;
export type CourseCategorySortField = (typeof courseCategorySortFields)[number];

export const lessonSortFields = ["id", "title", "contentType", "contentUrl", "contentText", "durationSeconds", "sortOrder", "isFreePreview", "chapterId"] as const;
export type LessonSortField = (typeof lessonSortFields)[number];

export const postSortFields = ["id", "title", "body", "insertedAt", "updatedAt", "coverImageUrl", "attachmentsUrls", "attachmentsThumbnailUrls"] as const;
export type PostSortField = (typeof postSortFields)[number];

export const organizationSortFields = ["id", "name", "slug", "schemaName", "contactEmail", "contactPhone", "description", "logoUrl", "status", "plan", "expiresAt"] as const;
export type OrganizationSortField = (typeof organizationSortFields)[number];

export const superAdminSortFields = ["id", "email", "name", "lastLoginAt"] as const;
export type SuperAdminSortField = (typeof superAdminSortFields)[number];

export const todoSortFields = ["id", "title", "completed", "insertedAt", "updatedAt"] as const;
export type TodoSortField = (typeof todoSortFields)[number];


// Utility Types

// Sort string type — allows optional direction prefix on sort field names
// Prefixes per Ash.Query.sort/3: + (asc), - (desc), ++ (asc_nils_first), -- (desc_nils_last)
export type SortString<T extends string> = T | `+${T}` | `-${T}` | `++${T}` | `--${T}`;

// Resource schema constraint
export type TypedSchema = {
  __type: "Resource" | "TypedMap" | "Union";
  __primitiveFields: string;
};

// Utility type to convert union to intersection
export type UnionToIntersection<U> = (U extends any ? (k: U) => void : never) extends (
  k: infer I,
) => void
  ? I
  : never;

// Helper type to infer union field values, avoiding duplication between array and non-array unions
export type InferUnionFieldValue<
  UnionSchema extends { __type: "Union"; __primitiveFields: any },
  FieldSelection extends any[],
> = UnionToIntersection<
  {
    [FieldIndex in keyof FieldSelection]: FieldSelection[FieldIndex] extends UnionSchema["__primitiveFields"]
      ? FieldSelection[FieldIndex] extends keyof UnionSchema
        ? { [P in FieldSelection[FieldIndex]]: UnionSchema[FieldSelection[FieldIndex]] }
        : never
      : FieldSelection[FieldIndex] extends Record<string, any>
        ? {
            [UnionKey in keyof FieldSelection[FieldIndex]]: UnionKey extends keyof UnionSchema
              ? NonNullable<UnionSchema[UnionKey]> extends { __array: true; __type: "TypedMap"; __primitiveFields: infer TypedMapFields }
                ? FieldSelection[FieldIndex][UnionKey] extends any[]
                  ? Array<
                      UnionToIntersection<
                        {
                          [FieldIdx in keyof FieldSelection[FieldIndex][UnionKey]]: FieldSelection[FieldIndex][UnionKey][FieldIdx] extends TypedMapFields
                            ? FieldSelection[FieldIndex][UnionKey][FieldIdx] extends keyof NonNullable<UnionSchema[UnionKey]>
                              ? { [P in FieldSelection[FieldIndex][UnionKey][FieldIdx]]: NonNullable<UnionSchema[UnionKey]>[P] }
                              : never
                            : never;
                        }[number]
                      >
                    > | null
                  : never
                : NonNullable<UnionSchema[UnionKey]> extends { __type: "TypedMap"; __primitiveFields: infer TypedMapFields }
                  ? FieldSelection[FieldIndex][UnionKey] extends any[]
                    ? UnionToIntersection<
                        {
                          [FieldIdx in keyof FieldSelection[FieldIndex][UnionKey]]: FieldSelection[FieldIndex][UnionKey][FieldIdx] extends TypedMapFields
                            ? FieldSelection[FieldIndex][UnionKey][FieldIdx] extends keyof NonNullable<UnionSchema[UnionKey]>
                              ? { [P in FieldSelection[FieldIndex][UnionKey][FieldIdx]]: NonNullable<UnionSchema[UnionKey]>[P] }
                              : never
                            : never;
                        }[number]
                      > | null
                    : never
                  : NonNullable<UnionSchema[UnionKey]> extends TypedSchema
                    ? InferResult<NonNullable<UnionSchema[UnionKey]>, FieldSelection[FieldIndex][UnionKey]>
                    : never
              : never;
          }
        : never;
  }[number]
>;

export type HasComplexFields<T extends TypedSchema> = keyof Omit<
  T,
  "__primitiveFields" | "__type" | T["__primitiveFields"]
> extends never
  ? false
  : true;

export type ComplexFieldKeys<T extends TypedSchema> = keyof Omit<
  T,
  "__primitiveFields" | "__type" | T["__primitiveFields"]
>;

export type LeafFieldSelection<T extends TypedSchema> = T["__primitiveFields"];

export type ComplexFieldSelection<T extends TypedSchema> = {
  [K in ComplexFieldKeys<T>]?: T[K] extends {
    __type: "Relationship";
    __resource: infer Resource;
  }
    ? NonNullable<Resource> extends TypedSchema
      ? UnifiedFieldSelection<NonNullable<Resource>>[]
      : never
    : T[K] extends {
          __type: "ComplexCalculation";
          __returnType: infer ReturnType;
        }
      ? T[K] extends { __args: infer Args }
        ? NonNullable<ReturnType> extends TypedSchema
          ? {
              args: Args;
              fields: UnifiedFieldSelection<NonNullable<ReturnType>>[];
            }
          : { args: Args }
        : NonNullable<ReturnType> extends TypedSchema
          ? { fields: UnifiedFieldSelection<NonNullable<ReturnType>>[] }
          : never
      : T[K] extends { __type: "TypedMap" }
        ? NonNullable<T[K]> extends TypedSchema
          ? UnifiedFieldSelection<NonNullable<T[K]>>[]
          : never
        : T[K] extends { __type: "Union"; __primitiveFields: infer PrimitiveFields }
          ? T[K] extends { __array: true }
            ? (PrimitiveFields | {
                [UnionKey in keyof Omit<T[K], "__type" | "__primitiveFields" | "__array">]?: NonNullable<T[K][UnionKey]> extends { __type: "TypedMap"; __primitiveFields: any }
                  ? NonNullable<T[K][UnionKey]>["__primitiveFields"][]
                  : NonNullable<T[K][UnionKey]> extends TypedSchema
                    ? UnifiedFieldSelection<NonNullable<T[K][UnionKey]>>[]
                    : never;
              })[]
            : (PrimitiveFields | {
                [UnionKey in keyof Omit<T[K], "__type" | "__primitiveFields">]?: NonNullable<T[K][UnionKey]> extends { __type: "TypedMap"; __primitiveFields: any }
                  ? NonNullable<T[K][UnionKey]>["__primitiveFields"][]
                  : NonNullable<T[K][UnionKey]> extends TypedSchema
                    ? UnifiedFieldSelection<NonNullable<T[K][UnionKey]>>[]
                    : never;
              })[]
            : NonNullable<T[K]> extends TypedSchema
              ? UnifiedFieldSelection<NonNullable<T[K]>>[]
              : never;
};

// Main type: Use explicit base case detection to prevent infinite recursion
export type UnifiedFieldSelection<T extends TypedSchema> =
  HasComplexFields<T> extends false
    ? LeafFieldSelection<T> // Base case: only primitives, no recursion
    : LeafFieldSelection<T> | ComplexFieldSelection<T>; // Recursive case

export type InferFieldValue<
  T extends TypedSchema,
  Field,
> = Field extends T["__primitiveFields"]
  ? Field extends keyof T
    ? { [K in Field]: T[Field] }
    : never
  : Field extends Record<string, any>
    ? {
        [K in keyof Field]: K extends keyof T
          ? T[K] extends {
              __type: "Relationship";
              __resource: infer Resource;
            }
            ? NonNullable<Resource> extends TypedSchema
              ? T[K] extends { __array: true }
                ? Array<InferResult<NonNullable<Resource>, Field[K]>>
                : null extends Resource
                  ? InferResult<NonNullable<Resource>, Field[K]> | null
                  : InferResult<NonNullable<Resource>, Field[K]>
            : never
          : T[K] extends {
                __type: "ComplexCalculation";
                __returnType: infer ReturnType;
              }
            ? NonNullable<ReturnType> extends TypedSchema
              ? null extends ReturnType
                ? InferResult<NonNullable<ReturnType>, Field[K]["fields"]> | null
                : InferResult<NonNullable<ReturnType>, Field[K]["fields"]>
              : ReturnType
            : NonNullable<T[K]> extends { __type: "TypedMap"; __primitiveFields: infer TypedMapFields }
              ? NonNullable<T[K]> extends { __array: true }
                ? Field[K] extends any[]
                  ? null extends T[K]
                    ? Array<
                        UnionToIntersection<
                          {
                            [FieldIndex in keyof Field[K]]: Field[K][FieldIndex] extends infer E
                              ? E extends TypedMapFields
                                ? E extends keyof NonNullable<T[K]>
                                  ? { [P in E]: NonNullable<T[K]>[P] }
                                  : never
                                : E extends Record<string, any>
                                  ? {
                                      [NestedKey in keyof E]: NestedKey extends keyof NonNullable<T[K]>
                                        ? NonNullable<NonNullable<T[K]>[NestedKey]> extends TypedSchema
                                          ? null extends NonNullable<T[K]>[NestedKey]
                                            ? InferResult<NonNullable<NonNullable<T[K]>[NestedKey]>, E[NestedKey]> | null
                                            : InferResult<NonNullable<NonNullable<T[K]>[NestedKey]>, E[NestedKey]>
                                          : never
                                        : never;
                                    }
                                  : E extends keyof NonNullable<T[K]>
                                    ? { [P in E]: NonNullable<T[K]>[P] }
                                    : never
                              : never;
                          }[number]
                        >
                      > | null
                    : Array<
                        UnionToIntersection<
                          {
                            [FieldIndex in keyof Field[K]]: Field[K][FieldIndex] extends infer E
                              ? E extends TypedMapFields
                                ? E extends keyof NonNullable<T[K]>
                                  ? { [P in E]: NonNullable<T[K]>[P] }
                                  : never
                                : E extends Record<string, any>
                                  ? {
                                      [NestedKey in keyof E]: NestedKey extends keyof NonNullable<T[K]>
                                        ? NonNullable<NonNullable<T[K]>[NestedKey]> extends TypedSchema
                                          ? null extends NonNullable<T[K]>[NestedKey]
                                            ? InferResult<NonNullable<NonNullable<T[K]>[NestedKey]>, E[NestedKey]> | null
                                            : InferResult<NonNullable<NonNullable<T[K]>[NestedKey]>, E[NestedKey]>
                                          : never
                                        : never;
                                    }
                                  : E extends keyof NonNullable<T[K]>
                                    ? { [P in E]: NonNullable<T[K]>[P] }
                                    : never
                              : never;
                          }[number]
                        >
                      >
                  : never
                : Field[K] extends any[]
                  ? null extends T[K]
                    ? UnionToIntersection<
                        {
                          [FieldIndex in keyof Field[K]]: Field[K][FieldIndex] extends infer E
                            ? E extends TypedMapFields
                              ? E extends keyof NonNullable<T[K]>
                                ? { [P in E]: NonNullable<T[K]>[P] }
                                : never
                              : E extends Record<string, any>
                                ? {
                                    [NestedKey in keyof E]: NestedKey extends keyof NonNullable<T[K]>
                                      ? NonNullable<NonNullable<T[K]>[NestedKey]> extends TypedSchema
                                        ? null extends NonNullable<T[K]>[NestedKey]
                                          ? InferResult<NonNullable<NonNullable<T[K]>[NestedKey]>, E[NestedKey]> | null
                                          : InferResult<NonNullable<NonNullable<T[K]>[NestedKey]>, E[NestedKey]>
                                        : never
                                      : never;
                                  }
                                : E extends keyof NonNullable<T[K]>
                                  ? { [P in E]: NonNullable<T[K]>[P] }
                                  : never
                            : never;
                        }[number]
                      > | null
                    : UnionToIntersection<
                        {
                          [FieldIndex in keyof Field[K]]: Field[K][FieldIndex] extends infer E
                            ? E extends TypedMapFields
                              ? E extends keyof T[K]
                                ? { [P in E]: T[K][P] }
                                : never
                              : E extends Record<string, any>
                                ? {
                                    [NestedKey in keyof E]: NestedKey extends keyof NonNullable<T[K]>
                                      ? NonNullable<NonNullable<T[K]>[NestedKey]> extends TypedSchema
                                        ? null extends NonNullable<T[K]>[NestedKey]
                                          ? InferResult<NonNullable<NonNullable<T[K]>[NestedKey]>, E[NestedKey]> | null
                                          : InferResult<NonNullable<NonNullable<T[K]>[NestedKey]>, E[NestedKey]>
                                        : never
                                      : never;
                                  }
                                : E extends keyof NonNullable<T[K]>
                                  ? { [P in E]: NonNullable<T[K]>[P] }
                                  : never
                            : never;
                        }[number]
                      >
                  : never
              : T[K] extends { __type: "Union"; __primitiveFields: any }
                ? T[K] extends { __array: true }
                  ? Field[K] extends any[]
                    ? null extends T[K]
                      ? Array<InferUnionFieldValue<T[K], Field[K]>> | null
                      : Array<InferUnionFieldValue<T[K], Field[K]>>
                    : never
                  : Field[K] extends any[]
                    ? null extends T[K]
                      ? InferUnionFieldValue<T[K], Field[K]> | null
                      : InferUnionFieldValue<T[K], Field[K]>
                    : never
                  : NonNullable<T[K]> extends TypedSchema
                    ? null extends T[K]
                      ? InferResult<NonNullable<T[K]>, Field[K]> | null
                      : InferResult<NonNullable<T[K]>, Field[K]>
                    : never
          : never;
      }
    : never;

export type InferResult<
  T extends TypedSchema,
  SelectedFields extends UnifiedFieldSelection<T>[] | undefined,
> = SelectedFields extends undefined
  ? {}
  : SelectedFields extends []
  ? {}
  : SelectedFields extends UnifiedFieldSelection<T>[]
  ? UnionToIntersection<
      {
        [K in keyof SelectedFields]: InferFieldValue<T, SelectedFields[K]>;
      }[number]
    >
  : {};

// Pagination conditional types
// Checks if a page configuration object has any pagination parameters
export type HasPaginationParams<Page> =
  Page extends { offset: any } ? true :
  Page extends { after: any } ? true :
  Page extends { before: any } ? true :
  false;

// Infer which pagination type is being used from the page config
export type InferPaginationType<Page> =
  Page extends { offset: any } ? "offset" :
  Page extends { after: any } | { before: any } ? "keyset" :
  never;

// Returns either non-paginated (array) or paginated result based on page params
// For single pagination type support (offset-only or keyset-only)
// @ts-ignore
// eslint-disable-next-line @typescript-eslint/no-unused-vars
export type ConditionalPaginatedResult<
  Page,
  RecordType,
  PaginatedType
> = Page extends undefined
  ? RecordType
  : HasPaginationParams<Page> extends true
    ? PaginatedType
    : RecordType;

// For actions supporting both offset and keyset pagination
// Infers the specific pagination type based on which params were passed
export type ConditionalPaginatedResultMixed<
  Page,
  RecordType,
  OffsetType,
  KeysetType
> = Page extends undefined
  ? RecordType
  : HasPaginationParams<Page> extends true
    ? InferPaginationType<Page> extends "offset"
      ? OffsetType
      : InferPaginationType<Page> extends "keyset"
        ? KeysetType
        : OffsetType | KeysetType  // Fallback to union if can't determine
    : RecordType;

export type SuccessDataFunc<T extends (...args: any[]) => Promise<any>> = Extract<
  Awaited<ReturnType<T>>,
  { success: true }
>["data"];


export type ErrorData<T extends (...args: any[]) => Promise<any>> = Extract<
  Awaited<ReturnType<T>>,
  { success: false }
>["errors"];

/**
 * Represents an error from an unsuccessful RPC call.
 *
 * This type matches the error structure defined in the AshTypescript.Rpc.Error protocol.
 *
 * @example
 * const error: AshRpcError = {
 *   type: "invalid_changes",
 *   message: "Invalid value for field %{field}",
 *   shortMessage: "Invalid changes",
 *   vars: { field: "email" },
 *   fields: ["email"],
 *   path: ["user", "email"],
 *   details: { suggestion: "Provide a valid email address" }
 * }
 */
export type AshRpcError = {
  /** Machine-readable error type (e.g., "invalid_changes", "not_found") */
  type: string;
  /** Full error message (may contain template variables like %{key}) */
  message: string;
  /** Concise version of the message */
  shortMessage: string;
  /** Variables to interpolate into the message template */
  vars: Record<string, any>;
  /** List of affected field names (for field-level errors) */
  fields: string[];
  /** Path to the error location in the data structure */
  path: string[];
  /** Optional map with extra details (e.g., suggestions, hints) */
  details?: Record<string, any>;
}

/**
 * Represents the result of a validation RPC call.
 *
 * All validation actions return this same structure, indicating either
 * successful validation or a list of validation errors.
 *
 * @example
 * // Successful validation
 * const result: ValidationResult = { success: true };
 *
 * // Failed validation
 * const result: ValidationResult = {
 *   success: false,
 *   errors: [
 *     {
 *       type: "required",
 *       message: "is required",
 *       shortMessage: "Required field",
 *       vars: { field: "email" },
 *       fields: ["email"],
 *       path: []
 *     }
 *   ]
 * };
 */
export type ValidationResult =
  | { success: true }
  | { success: false; errors: AshRpcError[]; };




