/**
 * Shared RPC client entry point.
 *
 * `ash_rpc.ts` / `ash_types.ts` / `ash_zod.ts` are generated by
 * `mix ash_typescript.codegen` — do not edit them manually.
 * `rpcHooks.ts` holds the shared auth lifecycle hooks (Bearer injection).
 */
export * from "./ash_rpc";
export * as RpcHooks from "./rpcHooks";
export * from "./sharedAuth";
