defmodule TcmEduWeb.CoreComponents do
  @moduledoc """
  Provides core UI components.

  Styling follows daisyUI semantics (`input`, `btn`, `label`, …) on top of
  the Tailwind v4 + daisyUI 5 pipeline in `assets/`. Icons render through
  the `hero-*` utilities generated by `assets/vendor/heroicons.js`; use
  `<.icon name="hero-x-mark" />`.
  """
  use Phoenix.Component

  alias Phoenix.LiveView.JS

  @doc """
  Renders flash notices.

  ## Examples

      <.flash kind={:info} flash={@flash} />
      <.flash id="welcome-back" kind={:info} phx-mounted={show("#welcome-back")} hidden>
        Welcome Back!
      </.flash>
  """
  attr :id, :string, default: nil
  attr :flash, :map, default: %{}, doc: "the map of flash messages to display"
  attr :title, :string, default: nil
  attr :kind, :atom, values: [:info, :error], doc: "used for styling and flash lookup"
  attr :rest, :global, include: ~w(phx-click phx-value-key)

  slot :inner_block, doc: "the optional inner block that renders the flash message"

  def flash(assigns) do
    assigns = assign_new(assigns, :id, fn -> "flash-#{assigns.kind}" end)

    ~H"""
    <div
      :if={msg = render_slot(@inner_block) || Phoenix.Flash.get(@flash, @kind)}
      id={@id}
      phx-click={JS.push("lv:clear-flash", value: %{key: @kind}) |> hide("##{@id}")}
      role="alert"
      class={[
        "fixed top-2 right-2 z-50 rounded-md px-3 py-2 shadow-md text-sm",
        @kind == :info && "bg-blue-100 text-blue-900 border border-blue-200",
        @kind == :error && "bg-red-100 text-red-900 border border-red-200"
      ]}
      {@rest}
    >
      <p :if={@title} class="font-semibold">{@title}</p>
      <p>{msg}</p>
    </div>
    """
  end

  @doc """
  Shows a Heroicon.

  Heroicons are generated as `hero-*` utilities by the Tailwind plugin in
  `assets/vendor/heroicons.js`. Use `<.icon name="hero-x-mark" />`.
  """
  attr :name, :string, required: true
  attr :class, :any, default: "size-4"

  def icon(%{name: "hero-" <> _} = assigns) do
    ~H"""
    <span class={[@name, @class]} aria-hidden="true" />
    """
  end

  @doc """
  Renders a header with title, optional subtitle, and action slot.
  """
  slot :inner_block, required: true
  slot :subtitle
  slot :actions

  def header(assigns) do
    ~H"""
    <header class={[@actions != [] && "flex items-center justify-between gap-6", "pb-4 border-b border-gray-200"]}>
      <div>
        <h1 class="text-lg font-semibold leading-8">
          {render_slot(@inner_block)}
        </h1>
        <p :if={@subtitle != []} class="text-sm text-gray-500">
          {render_slot(@subtitle)}
        </p>
      </div>
      <div class="flex-none">{render_slot(@actions)}</div>
    </header>
    """
  end

  @doc """
  Renders a data list with title/value pairs.
  """
  slot :item, required: true do
    attr :title, :string, required: true
  end

  def list(assigns) do
    ~H"""
    <dl class="divide-y divide-gray-200">
      <div :for={item <- @item} class="flex justify-between gap-4 py-2 text-sm">
        <dt class="text-gray-500">{item.title}</dt>
        <dd class="text-right font-mono">{render_slot(item)}</dd>
      </div>
    </dl>
    """
  end

  @doc """
  Renders a table with generic styling.
  """
  attr :id, :string, required: true
  attr :rows, :list, required: true

  slot :col, required: true do
    attr :label, :string
  end

  def table(assigns) do
    ~H"""
    <div class="overflow-x-auto">
      <table class="min-w-full text-sm">
        <thead class="bg-gray-50">
          <tr>
            <th
              :for={col <- @col}
              class="px-3 py-2 text-left font-medium text-gray-600"
            >
              {col[:label]}
            </th>
          </tr>
        </thead>
        <tbody id={@id} class="divide-y divide-gray-100">
          <tr :for={row <- @rows} class="hover:bg-gray-50">
            <td
              :for={col <- @col}
              class="px-3 py-2 align-top font-mono"
            >
              {render_slot(col, row)}
            </td>
          </tr>
        </tbody>
      </table>
    </div>
    """
  end

  @doc """
  Renders an input with a label and error messages, styled with daisyUI.

  A `Phoenix.HTML.FormField` may be passed as `field` to compute the input
  `id`, `name`, `value` and `errors` automatically:

      <.input field={@form[:email]} type="email" label="邮箱" />

  Supported types: all HTML text-like inputs plus `"select"`, `"textarea"`
  and `"checkbox"`.
  """
  attr :id, :any, default: nil
  attr :name, :any
  attr :label, :string, default: nil
  attr :value, :any

  attr :type, :string,
    default: "text",
    values: ~w(checkbox color date datetime-local email file month number password
               search select tel text textarea time url)

  attr :field, Phoenix.HTML.FormField,
    doc: "a form field struct retrieved from the form, e.g. @form[:email]"

  attr :errors, :list, default: []
  attr :checked, :boolean, doc: "the checked flag for checkbox inputs"
  attr :prompt, :string, default: nil, doc: "the prompt for select inputs"
  attr :options, :list, doc: "the options to pass to Phoenix.HTML.Form.options_for_select/2"
  attr :multiple, :boolean, default: false, doc: "the multiple flag for select inputs"

  attr :rest, :global,
    include: ~w(accept autocomplete capture cols disabled form list max maxlength
                min minlength multiple pattern placeholder readonly required rows size step)

  def input(%{field: %Phoenix.HTML.FormField{} = field} = assigns) do
    errors = if Phoenix.Component.used_input?(field), do: field.errors, else: []

    assigns
    |> assign(field: nil, id: assigns.id || field.id)
    |> assign(:errors, Enum.map(errors, &translate_error(&1)))
    |> assign_new(:name, fn -> if assigns.multiple, do: field.name <> "[]", else: field.name end)
    |> assign_new(:value, fn -> field.value end)
    |> input()
  end

  def input(%{type: "checkbox"} = assigns) do
    assigns =
      assign_new(assigns, :checked, fn ->
        Phoenix.HTML.Form.normalize_value("checkbox", assigns[:value])
      end)

    ~H"""
    <div class="form-control">
      <label class="label cursor-pointer justify-start gap-2" for={@id}>
        <input
          type="hidden"
          name={@name}
          value="false"
          disabled={@rest[:disabled]}
        />
        <input
          type="checkbox"
          id={@id}
          name={@name}
          value="true"
          checked={@checked}
          class="checkbox checkbox-primary"
          {@rest}
        />
        <span class="label-text">{@label}</span>
      </label>
      <.error :for={msg <- @errors}>{msg}</.error>
    </div>
    """
  end

  def input(%{type: "select"} = assigns) do
    ~H"""
    <div class="form-control w-full">
      <label class="label" for={@id}>
        <span class="label-text">{@label}</span>
      </label>
      <select
        id={@id}
        name={@name}
        class={["select select-bordered w-full", @errors != [] && "select-error"]}
        multiple={@multiple}
        {@rest}
      >
        <option :if={@prompt} value="">{@prompt}</option>
        {Phoenix.HTML.Form.options_for_select(@options, @value)}
      </select>
      <.error :for={msg <- @errors}>{msg}</.error>
    </div>
    """
  end

  def input(%{type: "textarea"} = assigns) do
    ~H"""
    <div class="form-control w-full">
      <label class="label" for={@id}>
        <span class="label-text">{@label}</span>
      </label>
      <textarea
        id={@id}
        name={@name}
        class={["textarea textarea-bordered w-full", @errors != [] && "textarea-error"]}
        {@rest}
      >{Phoenix.HTML.Form.normalize_value("textarea", @value)}</textarea>
      <.error :for={msg <- @errors}>{msg}</.error>
    </div>
    """
  end

  # All other inputs (text, email, password, number, …)
  def input(assigns) do
    ~H"""
    <div class="form-control w-full">
      <label class="label" for={@id}>
        <span class="label-text">{@label}</span>
      </label>
      <input
        type={@type}
        id={@id}
        name={@name}
        value={Phoenix.HTML.Form.normalize_value(@type, @value)}
        class={["input input-bordered w-full", @errors != [] && "input-error"]}
        {@rest}
      />
      <.error :for={msg <- @errors}>{msg}</.error>
    </div>
    """
  end

  @doc """
  Renders an error message below a form field using daisyUI error colors.
  """
  slot :inner_block, required: true

  def error(assigns) do
    ~H"""
    <p class="mt-1 text-xs text-error">
      <.icon name="hero-exclamation-circle" class="size-3.5" />
      {render_slot(@inner_block)}
    </p>
    """
  end

  @doc """
  Renders a button with daisyUI `btn` semantics.

      <.button>保存</.button>
      <.button class="btn-soft" phx-click="cancel">取消</.button>
  """
  attr :type, :string, default: nil
  attr :class, :string, default: "btn-primary"
  attr :rest, :global, include: ~w(disabled form name value phx-disable-with)

  slot :inner_block, required: true

  def button(assigns) do
    ~H"""
    <button type={@type} class={["btn", @class]} {@rest}>
      {render_slot(@inner_block)}
    </button>
    """
  end

  @doc """
  Translates an Ecto/Ash error message (`{msg, opts}`) into a plain string.
  """
  def translate_error({msg, opts}) do
    Enum.reduce(opts, msg, fn {key, value}, acc ->
      try do
        String.replace(acc, "%{#{key}}", fn _ -> to_string(value) end)
      rescue
        _ -> acc
      end
    end)
  end

  ## JS commands
  def show(js \\ %JS{}, selector) do
    JS.show(js,
      to: selector,
      time: 200,
      transition: {"transition-all ease-out duration-200", "opacity-0", "opacity-100"}
    )
  end

  def hide(js \\ %JS{}, selector) do
    JS.hide(js,
      to: selector,
      time: 150,
      transition: {"transition-all ease-in duration-150", "opacity-100", "opacity-0"}
    )
  end
end
