import Config

# Configure your database
config :tcm_edu, TcmEdu.Repo,
  username: System.get_env("PGUSER", "postgres"),
  password: System.get_env("PGPASSWORD", "postgres"),
  hostname: System.get_env("PGHOST", "localhost"),
  port: String.to_integer(System.get_env("PGPORT", "5433")),
  database: System.get_env("PGDATABASE", "postgres"),
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :tcm_edu, TcmEduWeb.Endpoint,
  # Binding to {0, 0, 0, 0} so LAN devices (physical phone running the APK)
  # can reach the API. `ip: {127, 0, 0, 1}` restricts it to this machine only.
  http: [ip: {0, 0, 0, 0}, port: 4011],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "Zb9OjGJToABRjI5xwCJrXOYoVL/KyLHtFHt1ttEtVqg04pPeZQNaLAOHpLM6choI",
  watchers: [
    npm: ["run", "watch:js", cd: Path.expand("../assets", __DIR__)],
    npm: ["run", "watch:css", cd: Path.expand("../assets", __DIR__)]
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Enable dev routes for dashboard and mailbox
config :tcm_edu, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime
