defmodule AshTsDemo.Repo.Migrations.MigrateResources5 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      remove :permissions
    end

    create table(:user_roles, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "user_roles_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :role_id, :uuid, null: false
    end

    create unique_index(:user_roles, [:user_id, :role_id],
             name: "user_roles_unique_user_role_index"
           )

    create table(:user_permissions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "user_permissions_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :permission_id, :uuid, null: false
    end

    create unique_index(:user_permissions, [:user_id, :permission_id],
             name: "user_permissions_unique_user_permission_index"
           )

    create table(:roles, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:user_roles) do
      modify :role_id,
             references(:roles,
               column: :id,
               name: "user_roles_role_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:roles) do
      add :name, :text, null: false
      add :description, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:roles, [:name], name: "roles_unique_role_name_index")

    create table(:role_permissions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :role_id,
          references(:roles,
            column: :id,
            name: "role_permissions_role_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :permission_id, :uuid, null: false
    end

    create unique_index(:role_permissions, [:role_id, :permission_id],
             name: "role_permissions_unique_role_permission_index"
           )

    create table(:permissions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:user_permissions) do
      modify :permission_id,
             references(:permissions,
               column: :id,
               name: "user_permissions_permission_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:role_permissions) do
      modify :permission_id,
             references(:permissions,
               column: :id,
               name: "role_permissions_permission_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:permissions) do
      add :name, :text, null: false
      add :description, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:permissions, [:name], name: "permissions_unique_permission_name_index")
  end

  def down do
    drop_if_exists unique_index(:permissions, [:name],
                     name: "permissions_unique_permission_name_index"
                   )

    alter table(:permissions) do
      remove :updated_at
      remove :inserted_at
      remove :description
      remove :name
    end

    drop constraint(:role_permissions, "role_permissions_permission_id_fkey")

    alter table(:role_permissions) do
      modify :permission_id, :uuid
    end

    drop constraint(:user_permissions, "user_permissions_permission_id_fkey")

    alter table(:user_permissions) do
      modify :permission_id, :uuid
    end

    drop table(:permissions)

    drop constraint(:role_permissions, "role_permissions_role_id_fkey")

    drop_if_exists unique_index(:role_permissions, [:role_id, :permission_id],
                     name: "role_permissions_unique_role_permission_index"
                   )

    drop table(:role_permissions)

    drop_if_exists unique_index(:roles, [:name], name: "roles_unique_role_name_index")

    alter table(:roles) do
      remove :updated_at
      remove :inserted_at
      remove :description
      remove :name
    end

    drop constraint(:user_roles, "user_roles_role_id_fkey")

    alter table(:user_roles) do
      modify :role_id, :uuid
    end

    drop table(:roles)

    drop constraint(:user_permissions, "user_permissions_user_id_fkey")

    drop_if_exists unique_index(:user_permissions, [:user_id, :permission_id],
                     name: "user_permissions_unique_user_permission_index"
                   )

    drop table(:user_permissions)

    drop constraint(:user_roles, "user_roles_user_id_fkey")

    drop_if_exists unique_index(:user_roles, [:user_id, :role_id],
                     name: "user_roles_unique_user_role_index"
                   )

    drop table(:user_roles)

    alter table(:users) do
      add :permissions, {:array, :text}, default: []
    end
  end
end
