defmodule TcmEdu.Repo.Migrations.UserAvatarAttachment do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:storage_user_attachments, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :record_type, :text, null: false
      add :record_id, :text, null: false

      add :blob_id,
          references(:storage_blobs,
            column: :id,
            name: "storage_user_attachments_blob_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end
  end

  def down do
    drop constraint(:storage_user_attachments, "storage_user_attachments_blob_id_fkey")

    drop table(:storage_user_attachments)
  end
end
