defmodule TcmEdu.Repo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:chat_tasks, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :task_id, :text, null: false
      add :user_id, :uuid, null: false
      add :session_id, :text, null: false
      add :agent_name, :text, null: false, default: "chat_agent"
      add :task_name, :text, null: false
      add :duration_ms, :bigint, null: false, default: 15000
      add :status, :text, null: false, default: "pending"
      add :job_id, :bigint
      add :result, :map
      add :error_message, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :started_at, :utc_datetime
      add :completed_at, :utc_datetime
    end
  end

  def down do
    drop table(:chat_tasks)
  end
end
