defmodule TcmEduWeb.AdminUserTemplateController do
  @moduledoc """
  Serves the bulk user-import template (`/admin/users/template`).

  Super admins (and tenant admins) download the template, fill it in,
  then upload it from the user-management page (`/admin/users`). The
  template is generated by `TcmEduWeb.AdminUserImport`.
  """

  use TcmEduWeb, :controller

  alias TcmEduWeb.AdminAuth
  alias TcmEduWeb.AdminUserImport

  plug :require_admin when action in [:template]

  def template(conn, _params) do
    send_download(conn, {:binary, AdminUserImport.template_xlsx()},
      filename: AdminUserImport.template_filename()
    )
  end

  defp require_admin(conn, _opts) do
    case AdminAuth.current_admin(get_session(conn)) do
      {:ok, _admin} ->
        conn

      :error ->
        conn
        |> put_flash(:error, "请先登录管理端")
        |> redirect(to: "/login")
        |> halt()
    end
  end
end
